services:
  # React App Service (SPA)
  react-app:
    build:
      context: ./react-app
      dockerfile: .Dockerfile
      args:
        - NODE_VERSION=${REACT_APP_NODE_VERSION}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: ${COMPOSE_PROJECT_NAME}_react-app
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks: [base2_network]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    tmpfs:
      - /var/cache/nginx
      - /var/run/nginx
      - /var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ > /dev/null || exit 1"]

  # FastAPI API (Option B: internal /health, external /api/health)
  api:
    build:
      context: ./api
      dockerfile: .Dockerfile
      args:
        - PYTHON_VERSION=${FASTAPI_PYTHON_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_api
    environment:
      - PORT=${FASTAPI_PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
    networks: [base2_network]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${FASTAPI_PORT}/health"]

  # Django (schema owner + admin)
  django:
    build:
      context: ./django
      dockerfile: .Dockerfile
      args:
        - PYTHON_VERSION=${DJANGO_PYTHON_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_django
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      # Django superuser bootstrap (used by `python -m project.create_superuser` in django/.Dockerfile)
      - DJANGO_SUPERUSER_NAME=${DJANGO_SUPERUSER_NAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${DJANGO_PORT}
    networks: [base2_network]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - django_static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--deploy"]

  # 🔹 Standalone NGINX (RESTORED)
  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - NGINX_PORT=${NGINX_PORT}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    environment:
      - NGINX_PORT=${NGINX_PORT}
    networks: [base2_network]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    read_only: false
    tmpfs:
      - /var/cache/nginx
      - /var/run/nginx
      - /var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${NGINX_PORT}/ > /dev/null || exit 1"]

  # Django static files
  nginx-static:
    image: nginx:1.25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_static
    volumes:
      - ./nginx/nginx-django-static.conf:/etc/nginx/nginx.conf:ro
      - django_static:/app/static:ro
    networks: [base2_network]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]

  # Traefik (ONLY public ports)
  traefik:
    build:
      context: .
      dockerfile: ./traefik/.Dockerfile
      args:
        - TRAEFIK_VERSION=${TRAEFIK_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    ports:
      - "80:80"
      - "443:443"
    networks: [base2_network]
    volumes:
      - ./letsencrypt:/etc/traefik/acme
      - traefik_logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - TRAEFIK_CERT_EMAIL=${TRAEFIK_CERT_EMAIL}
    restart: unless-stopped

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [base2_network]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  # pgAdmin (internal-only; routed via Traefik, guarded)
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
      - PGADMIN_LISTEN_PORT=${PGADMIN_PORT}
    networks: [base2_network]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${PGADMIN_PORT}/misc/ping > /dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  # Redis (internal-only; used by Celery)
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    networks: [base2_network]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Celery worker (optional; enable with `--profile celery`)
  celery-worker:
    build:
      context: ./api
      dockerfile: .Dockerfile
      args:
        - PYTHON_VERSION=${FASTAPI_PYTHON_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_celery_worker
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
      - CELERY_CONCURRENCY=${CELERY_CONCURRENCY}
    networks: [base2_network]
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-c", "celery -A tasks.app worker -l ${CELERY_LOG_LEVEL:-INFO} --concurrency=${CELERY_CONCURRENCY:-2}"]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os;from celery import Celery;app=Celery(broker=os.getenv('CELERY_BROKER_URL'));c=app.connection();c.connect();c.release();print('ok')\" || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10

  # Celery beat (optional; enable with `--profile celery`)
  celery-beat:
    build:
      context: ./api
      dockerfile: .Dockerfile
      args:
        - PYTHON_VERSION=${FASTAPI_PYTHON_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_celery_beat
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_LOG_LEVEL=${CELERY_LOG_LEVEL}
    networks: [base2_network]
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-c", "celery -A tasks.app beat -l ${CELERY_LOG_LEVEL:-INFO}"]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os;from celery import Celery;app=Celery(broker=os.getenv('CELERY_BROKER_URL'));c=app.connection();c.connect();c.release();print('ok')\" || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10

  # Flower (optional; enable with `--profile celery`; routed via Traefik, guarded)
  flower:
    image: mher/flower:2.0
    container_name: ${COMPOSE_PROJECT_NAME}_flower
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=5555
    networks: [base2_network]
    depends_on:
      redis:
        condition: service_healthy
    command: ["python", "-m", "flower", "--broker=${CELERY_BROKER_URL}", "flower", "--port=5555"]
    restart: unless-stopped
    security_opt: [no-new-privileges:true]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5555/ > /dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10


networks:
  base2_network:
    name: ${NETWORK_NAME}

volumes:
  postgres_data:
  django_static:
  pgadmin_data:
  traefik_logs:
