services:
  # React App Service
  react-app:
    build:
      context: ./react-app
      dockerfile: .Dockerfile
      args:
        - NODE_VERSION=${REACT_APP_NODE_VERSION}
        - REACT_APP_PORT=${REACT_APP_PORT}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: ${COMPOSE_PROJECT_NAME}_react-app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:${REACT_APP_PORT}', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile
      args:
        - NODE_VERSION=${BACKEND_NODE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
    networks:
      - base2_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:${BACKEND_PORT}/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Traefik Reverse Proxy Service
  traefik:
    build:
      context: ./traefik
      dockerfile: .Dockerfile
      args:
        - TRAEFIK_VERSION=${TRAEFIK_VERSION}
        - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL}
        - TRAEFIK_PORT=${TRAEFIK_PORT}
        - TRAEFIK_API_PORT=${TRAEFIK_API_PORT}
        - TRAEFIK_API_ENTRYPOINT=${TRAEFIK_API_ENTRYPOINT}
        - TRAEFIK_DOCKER_NETWORK=${TRAEFIK_DOCKER_NETWORK}
        - TRAEFIK_EXPOSED_BY_DEFAULT=${TRAEFIK_EXPOSED_BY_DEFAULT}
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    ports:
      - '${TRAEFIK_HOST_PORT}:${TRAEFIK_PORT}'
      - '${TRAEFIK_API_PORT}:${TRAEFIK_API_PORT}'
    environment:
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL}
      - TRAEFIK_PORT=${TRAEFIK_PORT}
      - TRAEFIK_API_PORT=${TRAEFIK_API_PORT}
      - TRAEFIK_API_ENTRYPOINT=${TRAEFIK_API_ENTRYPOINT}
      - TRAEFIK_DOCKER_NETWORK=${TRAEFIK_DOCKER_NETWORK}
      - TRAEFIK_EXPOSED_BY_DEFAULT=${TRAEFIK_EXPOSED_BY_DEFAULT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/var/log/traefik
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Nginx Web Server Service
  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
        - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
        - NGINX_PORT=${NGINX_PORT}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    environment:
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
      - NGINX_PORT=${NGINX_PORT}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(${WEBSITE_DOMAIN})"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
        - "traefik.http.routers.frontend-http.rule=Host(${WEBSITE_DOMAIN})"
        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:${NGINX_PORT}/']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # PostgreSQL Database Service
  postgres:
    build:
      context: ./postgres
      dockerfile: .Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - base2_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # pgAdmin Database Management Service
  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: .Dockerfile
      args:
        - PGADMIN_VERSION=${PGADMIN_VERSION}
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - base2_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(${WEBSITE_DOMAIN}) && PathPrefix(`/api`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=letsencrypt"
        - "traefik.http.services.api.loadbalancer.server.port=${BACKEND_PORT}"
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${PGADMIN_PORT}/misc/ping',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Networks Configuration
networks:
  base2_network:
    name: ${NETWORK_NAME}
    driver: bridge

# Volumes Configuration
volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data
    driver: local

  pgadmin_data:
    name: ${COMPOSE_PROJECT_NAME}_pgadmin_data
    driver: local

  traefik_logs:
    name: ${COMPOSE_PROJECT_NAME}_traefik_logs
    driver: local
