"""
render_traefik_dynamic.py

Renders traefik/dynamic.yml from a template, substituting ${VAR} with values from .env or environment variables.
Adds comment markers for idempotency.
"""
import os
import re
from pathlib import Path
from dotenv import dotenv_values

TEMPLATE_PATH = Path("traefik-dynamic.template.yml")
ENV_PATH = Path(".env")
OUTPUT_PATH = Path("traefik/dynamic.yml")
MARKER_START = "# --- BEGIN AUTO-GENERATED BY render_traefik_dynamic.py ---"
MARKER_END = "# --- END AUTO-GENERATED BY render_traefik_dynamic.py ---"

def load_env():
    env = dict(os.environ)
    if ENV_PATH.exists():
        env.update(dotenv_values(ENV_PATH))
    return env

def render_template(template, env):
    pattern = re.compile(r"\$\{([A-Za-z0-9_]+)\}")
    def replacer(match):
        var = match.group(1)
        return env.get(var, match.group(0))
    return pattern.sub(replacer, template)

def main():
    if not TEMPLATE_PATH.exists():
        print(f"Template file not found: {TEMPLATE_PATH}")
        return
    env = load_env()
    template = TEMPLATE_PATH.read_text()
    rendered = render_template(template, env)
    output = f"{MARKER_START}\n{rendered}\n{MARKER_END}\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output)
    print(f"Rendered {OUTPUT_PATH} from {TEMPLATE_PATH} using .env and environment variables.")

if __name__ == "__main__":
    main()
