#!/usr/bin/env python3
"""Generate integrity-bound, service-local site profiles from canonical manifests."""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.python.content_workspace_presets import compile_presets  # noqa: E402
from scripts.python.site_manifest import load_manifest, manifest_digest  # noqa: E402

TARGETS = (
    ROOT / "api" / "site_profiles",
    ROOT / "django" / "site_profiles",
    ROOT / "react-app" / "src" / "config" / "generated",
)
DEFAULT_PROFILE = "ember-studio"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        with contextlib.suppress(FileNotFoundError):
            os.unlink(temporary)


def generate(*, check: bool = False) -> dict[str, str]:
    profiles: dict[str, dict] = {}
    digests: dict[str, str] = {}
    for source in sorted((ROOT / "site_profiles").glob("*.json")):
        payload = load_manifest(source)
        profile_id = payload["siteId"]
        if source.stem != profile_id:
            raise ValueError(f"profile filename must equal siteId: {source.name}")
        profiles[profile_id] = payload
        digests[profile_id] = manifest_digest(payload)
    if not profiles:
        raise ValueError("at least one canonical site profile is required")

    outputs: dict[Path, str] = {}
    compiled_presets = compile_presets(ROOT / "modules/content-workspace/presets.json")
    compiled_preset_json = (
        json.dumps(compiled_presets, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )
    workspace_manifest = json.loads(
        (ROOT / "modules/content-workspace/module.json").read_text(encoding="utf-8")
    )
    workspace_contracts = {"schemaVersion": 1, "profiles": {}}
    for profile_id, profile in sorted(profiles.items()):
        enabled = any(
            item["id"] == "content-workspace" and item["enabled"] for item in profile["modules"]
        )
        workspace_contracts["profiles"][profile_id] = {
            "enabled": enabled,
            "models": workspace_manifest["models"] if enabled else [],
            "migrations": workspace_manifest["migrations"] if enabled else [],
            "apiRoutes": workspace_manifest["apiRoutes"] if enabled else [],
            "uiRoutes": workspace_manifest["uiRoutes"] if enabled else [],
            "navigation": workspace_manifest["navigation"] if enabled else [],
            "permissions": workspace_manifest["permissions"] if enabled else [],
            "jobs": workspace_manifest["jobs"] if enabled else [],
            "presets": sorted(compiled_presets["definitions"]) if enabled else [],
            "fixtures": [
                f"{preset_id}:synthetic-v1" for preset_id in sorted(compiled_presets["definitions"])
            ]
            if enabled
            else [],
            "contractTests": [
                "schema",
                "record",
                "workflow",
                "relationship",
                "media",
                "import-export",
                "public-renderer",
            ]
            if enabled
            else [],
            "migrationNotes": "versioned-forward-and-rollback-required"
            if enabled
            else "disabled-no-op",
        }
    workspace_contract_json = (
        json.dumps(workspace_contracts, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    )
    index = (
        json.dumps(
            {"schemaVersion": 1, "defaultProfile": DEFAULT_PROFILE, "profiles": digests},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    if DEFAULT_PROFILE not in profiles:
        raise ValueError(f"canonical default {DEFAULT_PROFILE} is missing")
    for target in TARGETS:
        outputs[target / "index.json"] = index
        outputs[target / "content-workspace-presets.json"] = compiled_preset_json
        outputs[target / "content-workspace-contracts.json"] = workspace_contract_json
        for profile_id, payload in profiles.items():
            outputs[target / f"{profile_id}.json"] = (
                json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
            )

    registry_lines = [
        "// Generated by scripts/python/generate_site_profiles.py; do not edit.",
        "import index from './index.json';",
    ]
    bindings = []
    for position, profile_id in enumerate(sorted(profiles)):
        binding = f"profile{position}"
        bindings.append((profile_id, binding))
        registry_lines.append(f"import {binding} from './{profile_id}.json';")
    registry_lines.extend(
        [
            "",
            "export { index };",
            "export const profiles: Record<string, unknown> = {",
            *[f"  '{profile_id}': {binding}," for profile_id, binding in bindings],
            "};",
            "",
        ]
    )
    outputs[ROOT / "react-app" / "src" / "config" / "generated" / "siteRegistry.ts"] = "\n".join(
        registry_lines
    )
    outputs[ROOT / "shared" / "config" / "content-workspace-presets.generated.json"] = (
        compiled_preset_json
    )

    stale: list[str] = []
    expected = set(outputs)
    for target in TARGETS:
        if target.exists():
            for path in target.glob("*.json"):
                if path not in expected:
                    stale.append(str(path.relative_to(ROOT)))
    for path, content in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(str(path.relative_to(ROOT)))
            if not check:
                _atomic_write(path, content)
    if check and stale:
        raise ValueError("generated site profiles are stale: " + ", ".join(sorted(set(stale))))
    return digests


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    digests = generate(check=args.check)
    print(json.dumps({"status": "current", "profiles": digests}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
