# Generated by GitHub Copilot on 2025-12-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_onetimetoken"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["actor_user"], name="users_audit_actor_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action"], name="users_audit_action_only_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["created"], name="users_audit_created_idx"),
        ),
    ]
