# Generated by Django 6.0 on 2026-01-01 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auditevent_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apitoken',
            new_name='users_apito_user_id_84f205_idx',
            old_name='users_token_active_idx',
        ),
        migrations.RenameIndex(
            model_name='emailaddress',
            new_name='users_email_email_77c813_idx',
            old_name='users_email_user_idx',
        ),
        migrations.RenameIndex(
            model_name='emailoutbox',
            new_name='users_email_to_9f9ec7_idx',
            old_name='users_to_sent_at_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimetoken',
            new_name='users_oneti_purpose_44a02d_idx',
            old_name='users_oneti_purpose_3e0793_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimetoken',
            new_name='users_oneti_user_id_f63cd1_idx',
            old_name='users_oneti_user_id_1b532f_idx',
        ),
        migrations.RenameIndex(
            model_name='onetimetoken',
            new_name='users_oneti_purpose_14af82_idx',
            old_name='users_oneti_purpose_9c3d98_idx',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default='', help_text='Latitude', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default='', help_text='Longitude', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, help_text='Postal Zip Code', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='Postal Zip Code'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_number',
            field=models.PositiveIntegerField(blank=True, help_text='Street Number', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='sub_premise',
            field=models.PositiveIntegerField(blank=True, help_text='Suite Number', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Suite Number'),
        ),
    ]
