# Generated by Django 6.0 on 2026-08-25 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_token_active_idx_users_apito_user_id_84f205_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('kind', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn')], max_length=16)),
                ('credential_id', models.CharField(blank=True, default='', max_length=512)),
                ('secret_ciphertext', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'credential_id'), name='users_authenticator_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'role', 'status'], name='users_membership_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='users_membership_org_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'email', 'expires_at'], name='users_invite_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('label', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'revoked_at'], name='users_credential_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='users_session_active_idx')],
            },
        ),
    ]
