# Generated by Django 6.1 on 2026-08-30 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_protect_audit_and_remove_oauth_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('event_family', models.CharField(choices=[('security', 'Security'), ('transactional', 'Transactional'), ('product', 'Product'), ('marketing', 'Marketing')], max_length=24)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In app'), ('browser', 'Browser')], max_length=16)),
                ('delivery', models.CharField(choices=[('immediate', 'Immediate'), ('digest', 'Digest'), ('disabled', 'Disabled')], max_length=16)),
                ('mandatory', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'organization', 'event_family'], name='users_notification_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('user', 'event_family', 'channel'), name='users_notification_user_default_uniq'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('user', 'organization', 'event_family', 'channel'), name='users_notification_owner_family_channel_uniq'), models.CheckConstraint(condition=models.Q(('mandatory', False), models.Q(('delivery', 'disabled'), _negated=True), _connector='OR'), name='users_notification_mandatory_delivery')],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created in database', verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-primary UUID identifier', unique=True, verbose_name='UUID')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=16)),
                ('contrast', models.CharField(choices=[('system', 'System'), ('standard', 'Standard'), ('high', 'High contrast')], default='system', max_length=16)),
                ('motion', models.CharField(choices=[('system', 'System'), ('full', 'Full motion'), ('reduced', 'Reduced motion')], default='system', max_length=16)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=16)),
                ('locale', models.CharField(default='en', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('week_start', models.CharField(choices=[('system', 'System'), ('monday', 'Monday'), ('sunday', 'Sunday'), ('saturday', 'Saturday')], default='system', max_length=16)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preference_sets', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'organization'], name='users_preferences_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('user',), name='users_preferences_user_default_uniq'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('user', 'organization'), name='users_preferences_owner_uniq'), models.CheckConstraint(condition=models.Q(('schema_version', 1)), name='users_preferences_schema_v1'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='users_preferences_ver_gte1')],
            },
        ),
    ]
