# Generated by Django 6.0 on 2026-08-25 10:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sitecontent.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecord',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.SlugField(max_length=64)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=240)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sitemap_include', models.BooleanField(default=True)),
                ('search_visible', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'state', 'publish_at'], name='sitecontent_publish_idx'), models.Index(fields=['site_id', 'content_type', 'updated_at'], name='sitecontent_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'content_type', 'slug'), name='sitecontent_record_slug_uq')],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_key', models.SlugField(max_length=100)),
                ('replay_key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('payload', models.JSONField(default=dict)),
                ('consent', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('queued', 'Queued'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='received', max_length=16)),
                ('retained_until', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'status', 'retained_until'], name='sitecontent_form_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'form_key', 'replay_key'), name='sitecontent_form_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=127)),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('quarantined', 'Quarantined'), ('deleted', 'Deleted')], default='pending', max_length=16)),
                ('owner_ref', models.CharField(max_length=200)),
                ('attribution', models.TextField(blank=True, default='')),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'status', 'created_at'], name='sitecontent_media_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'storage_key'), name='sitecontent_media_key_uq')],
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=500, validators=[sitecontent.models.validate_local_path])),
                ('target_path', models.CharField(max_length=500, validators=[sitecontent.models.validate_local_path])),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, 'Permanent'), (302, 'Temporary')], default=301)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'source_path'), name='sitecontent_redirect_uq')],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(default=dict)),
                ('actor_ref', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sitecontent.contentrecord')),
            ],
            options={
                'ordering': ['content_id', 'revision'],
                'constraints': [models.UniqueConstraint(fields=('content', 'revision'), name='sitecontent_revision_uq')],
            },
        ),
        migrations.CreateModel(
            name='FormDeliveryOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter', models.SlugField(default='disabled', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('dead_letter', 'Dead letter')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sitecontent.formsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='sitecontent_outbox_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=64)),
                ('storage_key', models.CharField(max_length=500)),
                ('media_type', models.CharField(max_length=127)),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sitecontent.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'name'), name='sitecontent_variant_uq')],
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('url_path', models.CharField(max_length=500, validators=[sitecontent.models.validate_local_path])),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('source_updated_at', models.DateTimeField()),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_document', to='sitecontent.contentrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'visibility', 'tombstoned_at'], name='sitecontent_search_idx')],
            },
        ),
    ]
