# Generated by Django 6.1 on 2026-09-02 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('actor_ref', models.CharField(max_length=200)),
                ('object_type', models.CharField(max_length=64)),
                ('object_ref', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentRecordVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitecontent.contentrevision',),
        ),
        migrations.AddField(
            model_name='contentrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentrecord',
            name='schema_version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='contentrecord',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='action',
            field=models.CharField(blank=True, default='update', max_length=32),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='restored_from_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='schema_version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='snapshot_sha256',
            field=models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')]),
        ),
        migrations.AlterField(
            model_name='contentrecord',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('in_review', 'In review'), ('deleted', 'Deleted')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='ContentTypeDefinition',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Use a lowercase identifier beginning with a letter.')])),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('migration_pending', 'Migration pending'), ('published', 'Published'), ('retired', 'Retired'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('preset_id', models.CharField(blank=True, default='', max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Use a lowercase identifier beginning with a letter.')])),
                ('preset_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('compatibility', models.CharField(blank=True, default='additive', max_length=24)),
                ('migration_digest', models.CharField(blank=True, default='', max_length=64)),
                ('lock_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'type_key', 'status'], name='sitecontent_type_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'type_key', 'version'), name='sitecontent_type_version_uq')],
            },
        ),
        migrations.AddField(
            model_name='contentrecord',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sitecontent.contenttypedefinition'),
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_ref', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=120)),
                ('query', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('role_shared', 'role_shared')], default='private', max_length=16)),
                ('shared_roles', models.JSONField(blank=True, default=list)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='sitecontent.contenttypedefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('states', models.JSONField(default=list)),
                ('initial_state', models.CharField(default='draft', max_length=24)),
                ('transitions', models.JSONField(default=list)),
                ('definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='sitecontent.contenttypedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='AssetBinding',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Use a lowercase identifier beginning with a letter.')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('caption', models.TextField(blank=True, default='')),
                ('credit', models.CharField(blank=True, default='', max_length=500)),
                ('focal_x', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('focal_y', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_bindings', to='sitecontent.mediaasset')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bindings', to='sitecontent.contentrecord')),
            ],
            options={
                'ordering': ['record_id', 'field_key', 'order'],
                'constraints': [models.UniqueConstraint(fields=('record', 'field_key', 'asset'), name='sitecontent_asset_binding_uq')],
            },
        ),
        migrations.CreateModel(
            name='ContentRelationship',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Use a lowercase identifier beginning with a letter.')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('deletion_policy', models.CharField(choices=[('restrict', 'restrict'), ('detach', 'detach'), ('cascade_soft', 'cascade_soft')], default='restrict', max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='sitecontent.contentrecord')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='sitecontent.contentrecord')),
            ],
            options={
                'ordering': ['source_id', 'field_key', 'order', 'target_id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'field_key', 'target'), name='sitecontent_relationship_uq'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='sitecontent_no_self_rel')],
            },
        ),
        migrations.CreateModel(
            name='ContentFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{1,62}$', 'Use a lowercase identifier beginning with a letter.')])),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('field_kind', models.CharField(choices=[('short_text', 'short_text'), ('long_text', 'long_text'), ('rich_text', 'rich_text'), ('integer', 'integer'), ('decimal', 'decimal'), ('boolean', 'boolean'), ('date', 'date'), ('datetime', 'datetime'), ('enum', 'enum'), ('slug', 'slug'), ('url', 'url'), ('email', 'email'), ('location', 'location'), ('reference', 'reference'), ('references', 'references'), ('image', 'image'), ('file', 'file'), ('json_object', 'json_object')], max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('nullable', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('presentation', models.JSONField(blank=True, default=dict)),
                ('indexed', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('read_permission', models.CharField(default='content.read', max_length=64)),
                ('write_permission', models.CharField(default='content.write', max_length=64)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sitecontent.contenttypedefinition')),
            ],
            options={
                'ordering': ['definition_id', 'order', 'field_key'],
                'constraints': [models.UniqueConstraint(fields=('definition', 'field_key'), name='sitecontent_field_key_uq')],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_ref', models.CharField(max_length=200)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('idempotency_key', models.CharField(max_length=128)),
                ('schema_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='queued', max_length=16)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=8)),
                ('projection_digest', models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('output_sha256', models.CharField(blank=True, default='', max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('encrypted_object_key', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitecontent.contenttypedefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'idempotency_key'), name='sitecontent_export_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_ref', models.CharField(max_length=200)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('idempotency_key', models.CharField(max_length=128)),
                ('schema_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('parsing', 'parsing'), ('mapped', 'mapped'), ('validated', 'validated'), ('review_required', 'review_required'), ('committing', 'committing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='uploaded', max_length=24)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('duplicate_policy', models.CharField(default='review', max_length=16)),
                ('atomic_policy', models.CharField(default='all_or_nothing', max_length=16)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitecontent.contenttypedefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'idempotency_key'), name='sitecontent_import_replay_uq')],
            },
        ),
    ]
