# Generated by Django 6.1 on 2026-09-02 16:26

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0003_workspace_row_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentrelationship",
            name="maximum_depth",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AddField(
            model_name="contentrelationship",
            name="maximum_items",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="contentrelationship",
            name="target_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=63,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z][a-z0-9_]{1,62}$",
                        "Use a lowercase identifier beginning with a letter.",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ImportRowOutcome",
            fields=[
                (
                    "site_id",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9-]{2,62}$", "Enter a canonical site identifier."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ordinal",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "source_row_sha256",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-f0-9]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "proposed_action",
                    models.CharField(
                        choices=[
                            ("create", "create"),
                            ("update", "update"),
                            ("skip", "skip"),
                            ("review", "review"),
                            ("reject", "reject"),
                        ],
                        max_length=16,
                    ),
                ),
                ("field_issues", models.JSONField(blank=True, default=list)),
                ("exact_match_id", models.UUIDField(blank=True, null=True)),
                ("candidate_ids", models.JSONField(blank=True, default=list)),
                ("result_record_id", models.UUIDField(blank=True, null=True)),
                ("result_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_outcomes",
                        to="sitecontent.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "ordinal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "ordinal"), name="sitecontent_import_row_ordinal_uq"
                    )
                ],
            },
        ),
    ]
