# Generated by Django 6.1 on 2026-09-06 09:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0010_workspace_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('owner_ref', models.CharField(max_length=200)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('role_shared', 'Role shared')], default='private', max_length=16)),
                ('shared_roles', models.JSONField(blank=True, default=list)),
                ('lock_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='current_object_version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='lock_version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('authenticated', 'Authenticated'), ('public', 'Public')], default='private', max_length=16),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='inline_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='processor_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='recipe_id',
            field=models.CharField(blank=True, default='legacy-safe-v1', max_length=64),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='recipe_version',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='source_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('inspecting', 'Inspecting'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('validated', 'Validated'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('soft_deleted', 'Soft deleted'), ('purge_planned', 'Purge planned'), ('purged', 'Purged')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='MediaRetentionHold',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=64)),
                ('owner_ref', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_holds', to='sitecontent.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaUploadSession',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ref', models.CharField(max_length=200)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('expected_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('expected_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('receiving', 'Receiving'), ('uploaded', 'Uploaded'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'status', 'expires_at'], name='media_upload_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'actor_ref', 'idempotency_key'), name='sitecontent_media_upload_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaCollectionMembership',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='sitecontent.mediaasset')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sitecontent.mediacollection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collection', 'asset'), name='sitecontent_media_collection_asset_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('inspect', 'Inspect'), ('derive', 'Derive'), ('reconcile', 'Reconcile'), ('export', 'Export'), ('expire', 'Expire'), ('purge', 'Purge')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('running', 'Running'), ('completed', 'Completed'), ('retryable', 'Retryable'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('maximum_attempts', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sitecontent.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'kind', 'idempotency_key'), name='sitecontent_media_job_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaMetadataRevision',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('locale', models.CharField(default='en', max_length=32)),
                ('alt_text', models.CharField(blank=True, default='', max_length=500)),
                ('decorative', models.BooleanField(default=False)),
                ('caption', models.TextField(blank=True, default='')),
                ('credit', models.CharField(blank=True, default='', max_length=500)),
                ('license_code', models.CharField(blank=True, default='', max_length=64)),
                ('focal_x', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('focal_y', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('actor_ref', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metadata_revisions', to='sitecontent.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'revision', 'locale'), name='sitecontent_media_metadata_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaObjectVersion',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_key', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('detected_type', models.CharField(max_length=127)),
                ('inspection_state', models.CharField(choices=[('uploaded', 'Uploaded'), ('inspecting', 'Inspecting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('scanner_ref', models.CharField(blank=True, default='', max_length=128)),
                ('scanner_definitions_at', models.DateTimeField(blank=True, null=True)),
                ('source_upload_ref', models.UUIDField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_versions', to='sitecontent.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'version'), name='sitecontent_media_object_version_uq'), models.UniqueConstraint(fields=('site_id', 'storage_key'), name='sitecontent_media_object_key_uq')],
            },
        ),
    ]
