# Generated by Django 6.1 on 2026-09-06 12:05

import os
import re
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

ROLE_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,62}$")
MEDIA_GOVERNANCE_TABLES = (
    "sitecontent_mediaauditevent",
    "sitecontent_mediadeliverygrant",
    "sitecontent_mediaexportpackage",
    "sitecontent_mediaoutboxevent",
    "sitecontent_mediareference",
)


def _roles(schema_editor):
    runtime = os.environ.get("WORKSPACE_DB_USER", "").strip()
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE_NAME.fullmatch(runtime) or not ROLE_NAME.fullmatch(worker) or runtime == worker:
        raise RuntimeError("media_governance_role_invalid")
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname=%s", (role,))
            if not cursor.fetchone():
                raise RuntimeError("media_governance_role_missing")
    quote = schema_editor.connection.ops.quote_name
    return quote(runtime), quote(worker), f"'{worker}'"


def configure_media_governance_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute(f"GRANT USAGE ON SCHEMA public TO {role}")
        for table in MEDIA_GOVERNANCE_TABLES:
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {runtime}')
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {worker}')
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''CREATE POLICY "{policy}" ON "{table}"
                    USING (site_id = current_setting('app.tenant_id', true)
                           OR current_user = {worker_literal})
                    WITH CHECK (site_id = current_setting('app.tenant_id', true)
                                OR current_user = {worker_literal})'''
            )


def remove_media_governance_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, _worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(MEDIA_GOVERNANCE_TABLES):
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {worker}')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {runtime}')


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0012_universal_media_library_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAuditEvent',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('event_type', models.CharField(max_length=64)),
                ('actor_ref', models.CharField(max_length=200)),
                ('subject_ref', models.CharField(max_length=200)),
                ('detail', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('event_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'sequence'), name='sitecontent_media_audit_seq_uq'), models.UniqueConstraint(fields=('site_id', 'event_hash'), name='sitecontent_media_audit_hash_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaExportPackage',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(max_length=200)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('binary', 'Binary')], max_length=8)),
                ('projection', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('artifact_key', models.CharField(blank=True, default='', max_length=500)),
                ('artifact_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('expires_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'requested_by', 'request_digest'), name='sitecontent_media_export_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaOutboxEvent',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_ref', models.CharField(max_length=200)),
                ('event_kind', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('leased', 'Leased'), ('completed', 'Completed'), ('retryable', 'Retryable'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('maximum_attempts', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'status', 'available_at'], name='media_outbox_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'event_kind', 'idempotency_key'), name='sitecontent_media_outbox_replay_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaDeliveryGrant',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD')], max_length=4)),
                ('audience_ref', models.CharField(max_length=200)),
                ('token_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('authorization_epoch', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_grants', to='sitecontent.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'asset', 'expires_at'], name='media_grant_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'token_digest'), name='sitecontent_media_grant_digest_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaReference',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.SlugField(max_length=64)),
                ('owner_id', models.UUIDField()),
                ('field_key', models.SlugField(max_length=100)),
                ('owner_state', models.CharField(max_length=32)),
                ('owner_visibility', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Authenticated'), ('public', 'Public')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('lock_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='sitecontent.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'asset', 'owner_state'], name='media_reference_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'asset', 'owner_type', 'owner_id', 'field_key'), name='sitecontent_media_reference_uq')],
            },
        ),
        migrations.RunPython(configure_media_governance_roles, remove_media_governance_roles),
    ]
