# Generated by Django 6.1 on 2026-09-06 12:12

import os
import re
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

ROLE_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,62}$")
MEDIA_PROCESSING_TABLES = (
    "sitecontent_mediainspectionresult",
    "sitecontent_mediapurgeplan",
    "sitecontent_mediauploadpart",
)


def _roles(schema_editor):
    runtime = os.environ.get("WORKSPACE_DB_USER", "").strip()
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE_NAME.fullmatch(runtime) or not ROLE_NAME.fullmatch(worker) or runtime == worker:
        raise RuntimeError("media_processing_role_invalid")
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname=%s", (role,))
            if not cursor.fetchone():
                raise RuntimeError("media_processing_role_missing")
    quote = schema_editor.connection.ops.quote_name
    return quote(runtime), quote(worker), f"'{worker}'"


def configure_media_processing_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute(f"GRANT USAGE ON SCHEMA public TO {role}")
        for table in MEDIA_PROCESSING_TABLES:
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {runtime}')
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {worker}')
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''CREATE POLICY "{policy}" ON "{table}"
                    USING (site_id = current_setting('app.tenant_id', true)
                           OR current_user = {worker_literal})
                    WITH CHECK (site_id = current_setting('app.tenant_id', true)
                                OR current_user = {worker_literal})'''
            )


def remove_media_processing_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, _worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(MEDIA_PROCESSING_TABLES):
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {worker}')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {runtime}')


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0013_media_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDerivativeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.SlugField(max_length=64)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('output_media_type', models.CharField(max_length=127)),
                ('processor_ref', models.CharField(max_length=128)),
                ('parameters', models.JSONField(default=dict)),
                ('recipe_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe_id', 'version'), name='sitecontent_media_recipe_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaInspectionResult',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('failed', 'Failed')], max_length=16)),
                ('safe_code', models.CharField(max_length=64)),
                ('scanner_ref', models.CharField(max_length=128)),
                ('decoder_ref', models.CharField(max_length=128)),
                ('definitions_at', models.DateTimeField()),
                ('observed_media_type', models.CharField(max_length=127)),
                ('measurements', models.JSONField(default=dict)),
                ('result_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('object_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to='sitecontent.mediaobjectversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('object_version', 'attempt'), name='sitecontent_media_inspection_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaPurgePlan',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(max_length=200)),
                ('reason_code', models.CharField(max_length=64)),
                ('expected_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('object_manifest', models.JSONField(default=list)),
                ('reference_preview', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purge_plans', to='sitecontent.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'asset', 'expected_version'), name='sitecontent_media_purge_plan_uq')],
            },
        ),
        migrations.CreateModel(
            name='MediaUploadPart',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('byte_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('storage_key', models.CharField(max_length=500)),
                ('completed_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sitecontent.mediauploadsession')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'session', 'part_number'], name='media_part_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'part_number'), name='sitecontent_media_upload_part_uq'), models.UniqueConstraint(fields=('site_id', 'storage_key'), name='sitecontent_media_part_key_uq')],
            },
        ),
        migrations.RunPython(configure_media_processing_roles, remove_media_processing_roles),
    ]
