# Generated by Django 6.1 on 2026-09-06 12:35

import os
import re
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

ROLE_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,62}$")
MEDIA_PORTABILITY_TABLES = (
    "sitecontent_mediaabusecase",
    "sitecontent_mediaencryptionenvelope",
)


def _roles(schema_editor):
    runtime = os.environ.get("WORKSPACE_DB_USER", "").strip()
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE_NAME.fullmatch(runtime) or not ROLE_NAME.fullmatch(worker) or runtime == worker:
        raise RuntimeError("media_portability_role_invalid")
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname=%s", (role,))
            if not cursor.fetchone():
                raise RuntimeError("media_portability_role_missing")
    quote = schema_editor.connection.ops.quote_name
    return quote(runtime), quote(worker), f"'{worker}'"


def configure_media_portability_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for role in (runtime, worker):
            cursor.execute(f"GRANT USAGE ON SCHEMA public TO {role}")
        for table in MEDIA_PORTABILITY_TABLES:
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {runtime}')
            cursor.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "{table}" TO {worker}')
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(
                f'''CREATE POLICY "{policy}" ON "{table}"
                    USING (site_id = current_setting('app.tenant_id', true)
                           OR current_user = {worker_literal})
                    WITH CHECK (site_id = current_setting('app.tenant_id', true)
                                OR current_user = {worker_literal})'''
            )


def remove_media_portability_roles(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    runtime, worker, _worker_literal = _roles(schema_editor)
    with schema_editor.connection.cursor() as cursor:
        for table in reversed(MEDIA_PORTABILITY_TABLES):
            policy = f"{table}_tenant_scope"
            cursor.execute(f'DROP POLICY IF EXISTS "{policy}" ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {worker}')
            cursor.execute(f'REVOKE ALL PRIVILEGES ON TABLE "{table}" FROM {runtime}')


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0014_media_processing_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='authorization_epoch',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mediajob',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediajob',
            name='output_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='ordering_hint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mediametadatarevision',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaobjectversion',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='sitecontent.mediaobjectversion'),
        ),
        migrations.AddField(
            model_name='mediareference',
            name='content_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_references', to='sitecontent.contentrecord'),
        ),
        migrations.AddField(
            model_name='mediauploadsession',
            name='terminal_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mediavariant',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MediaEncryptionEnvelope',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_ref', models.CharField(max_length=160)),
                ('key_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('wrapped_data_key_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('object_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='encryption_envelope', to='sitecontent.mediaobjectversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAbuseCase',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_ref', models.CharField(max_length=200)),
                ('reviewer_ref', models.CharField(blank=True, default='', max_length=200)),
                ('appellant_ref', models.CharField(blank=True, default='', max_length=200)),
                ('reason_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('quarantined', 'Quarantined'), ('dismissed', 'Dismissed'), ('appealed', 'Appealed'), ('restored', 'Restored'), ('removed', 'Removed')], default='reported', max_length=16)),
                ('lock_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abuse_cases', to='sitecontent.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'status', 'created_at'], name='media_abuse_idx')],
            },
        ),
        migrations.RunPython(configure_media_portability_roles, remove_media_portability_roles),
    ]
