# Generated by Django 6.1 on 2026-09-08 05:49

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0019_operations_center_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_key', models.CharField(choices=[('users', 'Users'), ('storage', 'Storage'), ('media', 'Media'), ('api', 'Api'), ('jobs', 'Jobs'), ('email', 'Email'), ('search', 'Search'), ('cost', 'Cost')], max_length=16)),
                ('limit', models.PositiveBigIntegerField()),
                ('used', models.PositiveBigIntegerField(default=0)),
                ('reserved', models.PositiveBigIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'quota_key'), name='tenant_quota_scope_uq'), models.CheckConstraint(condition=models.Q(('used__lte', models.F('limit'))), name='tenant_quota_used_lte_limit'), models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('limit'))), name='tenant_quota_reserved_lte_limit'), models.CheckConstraint(condition=models.Q(('used__lte', django.db.models.expressions.CombinedExpression(models.F('limit'), '-', models.F('reserved')))), name='tenant_quota_total_lte_limit')],
            },
        ),
        migrations.CreateModel(
            name='TenantQuotaReservation',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_id', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('released', 'Released')], default='reserved', max_length=16)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sitecontent.tenantquota')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'reservation_id'), name='tenant_quota_reservation_scope_uq')],
            },
        ),
    ]
