# Generated by Django 6.1 on 2026-09-08 06:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0021_quota_rls_and_operations_worker_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomainClaim',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('challenge_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('evidence_digest', models.CharField(blank=True, default='', max_length=64)),
                ('approval_digest', models.CharField(blank=True, default='', max_length=64)),
                ('release_id', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('canonical', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'state', 'domain'], name='tenant_domain_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('canonical', True), ('state', 'active')), fields=('site_id',), name='tenant_one_active_canonical_uq')],
            },
        ),
    ]
