# Generated by Django 6.1 on 2026-09-08 06:45

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0023_tenant_domain_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakGlassGrant',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_ref', models.CharField(max_length=200)),
                ('approver_ref', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('reason_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('approval_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DurableJob',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_ref', models.CharField(max_length=200)),
                ('generation', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('job_type', models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('payload_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('payload_schema', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('idempotency_key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('succeeded', 'Succeeded'), ('retry', 'Retry'), ('dead_letter', 'Dead Letter'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('maximum_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=200)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('result_digest', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=96)),
            ],
            options={
                'indexes': [models.Index(fields=['site_id', 'state', 'available_at'], name='durable_job_ready_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'idempotency_key'), name='durable_job_replay_uq'), models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('maximum_attempts'))), name='durable_job_attempts_lte_max')],
            },
        ),
        migrations.CreateModel(
            name='DurableSchedule',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_key', models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('job_type', models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('rule', models.CharField(max_length=128)),
                ('missed_policy', models.CharField(choices=[('skip', 'Skip'), ('once', 'Once')], default='once', max_length=16)),
                ('overlap_policy', models.CharField(choices=[('forbid', 'Forbid'), ('replace', 'Replace')], default='forbid', max_length=16)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'schedule_key'), name='durable_schedule_scope_uq')],
            },
        ),
        migrations.CreateModel(
            name='TenantNotification',
            fields=[
                ('site_id', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{2,62}$', 'Enter a canonical site identifier.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_ref', models.CharField(max_length=200)),
                ('event_key', models.CharField(max_length=96, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('family', models.CharField(choices=[('security', 'Security'), ('transactional', 'Transactional'), ('product', 'Product')], max_length=16)),
                ('channel', models.CharField(choices=[('in_app', 'In_App'), ('email', 'Email')], max_length=16)),
                ('content_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('idempotency_key', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_.-]{2,95}$', 'Use a bounded lowercase operations identifier.')])),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'idempotency_key', 'channel'), name='tenant_notification_replay_uq')],
            },
        ),
    ]
