# Generated by Django 6.1 on 2026-09-08 08:10

import os
import re

from django.db import migrations, models
from django.utils import timezone

ROLE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,62}$")
JOB_IDENTITY = re.compile(r"^[a-z][a-z0-9_.:-]{2,127}$")
JOB_TYPE = re.compile(r"^[a-z][a-z0-9_.:-]{2,95}$")
DIGEST = re.compile(r"^[0-9a-f]{64}$")


def narrow_worker_grants(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE.fullmatch(worker):
        raise RuntimeError("runtime:workspace_worker_db_user_invalid")
    quoted = schema_editor.connection.ops.quote_name(worker)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'REVOKE INSERT, UPDATE ON TABLE "sitecontent_tenantdomainclaim" FROM {quoted}'
        )
        cursor.execute(
            f'REVOKE INSERT, UPDATE ON TABLE "sitecontent_breakglassgrant" FROM {quoted}'
        )
        cursor.execute(f'REVOKE INSERT ON TABLE "sitecontent_durableschedule" FROM {quoted}')
        cursor.execute(f'REVOKE INSERT ON TABLE "sitecontent_tenantnotification" FROM {quoted}')


def restore_worker_grants(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE.fullmatch(worker):
        raise RuntimeError("runtime:workspace_worker_db_user_invalid")
    quoted = schema_editor.connection.ops.quote_name(worker)
    with schema_editor.connection.cursor() as cursor:
        for table in (
            "sitecontent_tenantdomainclaim",
            "sitecontent_breakglassgrant",
            "sitecontent_durableschedule",
            "sitecontent_tenantnotification",
        ):
            cursor.execute(f'GRANT INSERT, UPDATE ON TABLE "{table}" TO {quoted}')


def recover_legacy_job_leases(apps, schema_editor):
    """Clear leases that predate the cryptographic lease-token invariant."""
    durable_job = apps.get_model("sitecontent", "DurableJob")
    durable_job.objects.using(schema_editor.connection.alias).filter(state="leased").update(
        state="retry",
        lease_owner="",
        lease_expires_at=None,
        error_code="job.lease_upgrade_recovery",
        updated_at=timezone.now(),
    )


def normalize_legacy_invalid_jobs(apps, schema_editor):
    """Quarantine rows accepted by the older permissive repository contract."""
    durable_job = apps.get_model("sitecontent", "DurableJob")
    database = schema_editor.connection.alias
    for job in durable_job.objects.using(database).all().iterator(chunk_size=500):
        invalid = (
            not JOB_IDENTITY.fullmatch(job.owner_ref or "")
            or not JOB_TYPE.fullmatch(job.job_type or "")
            or not JOB_IDENTITY.fullmatch(job.idempotency_key or "")
            or not DIGEST.fullmatch(job.payload_digest or "")
            or bool(job.result_digest)
            and not DIGEST.fullmatch(job.result_digest)
        )
        if not invalid:
            continue
        durable_job.objects.using(database).filter(pk=job.pk).update(
            owner_ref=(
                job.owner_ref if JOB_IDENTITY.fullmatch(job.owner_ref or "") else f"legacy:{job.pk}"
            ),
            job_type=(job.job_type if JOB_TYPE.fullmatch(job.job_type or "") else "legacy.invalid"),
            idempotency_key=(
                job.idempotency_key
                if JOB_IDENTITY.fullmatch(job.idempotency_key or "")
                else f"legacy:{job.pk}"
            ),
            payload_digest=(
                job.payload_digest if DIGEST.fullmatch(job.payload_digest or "") else "0" * 64
            ),
            result_digest=(job.result_digest if DIGEST.fullmatch(job.result_digest or "") else ""),
            state="dead_letter",
            lease_owner="",
            lease_token=None,
            lease_expires_at=None,
            error_code="job.legacy_identity_invalid",
            updated_at=timezone.now(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0025_runtime_governance_rls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="operationsincident",
            name="operations_incident_scope_uq",
        ),
        migrations.AddField(
            model_name="durablejob",
            name="lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="durableschedule",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="durableschedule",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsalertdelivery",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsalertdelivery",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsincident",
            name="environment",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("preview", "Preview"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="operationsalertdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("acknowledged", "Acknowledged"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        # A pre-0026 lease has no cryptographic lease token. It cannot be
        # safely grandfathered, so make it retryable and clear its stale lease
        # before enforcing the new all-or-nothing lease invariant.
        migrations.RunPython(recover_legacy_job_leases, migrations.RunPython.noop),
        # The pre-0026 repository validated only non-emptiness and digest
        # length. Quarantine those legacy rows before PostgreSQL validates the
        # stricter durable identity constraints below.
        migrations.RunPython(normalize_legacy_invalid_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="breakglassgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("requester_ref", models.F("approver_ref")), _negated=True),
                name="break_glass_independent_approver_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durablejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("state", "leased"),
                        models.Q(("lease_owner", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("state", "leased"), _negated=True),
                        ("lease_owner", ""),
                        ("lease_token__isnull", True),
                        ("lease_expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="durable_job_lease_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durableschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("claim_expires_at__isnull", True), ("claim_token__isnull", True)),
                    models.Q(("claim_expires_at__isnull", False), ("claim_token__isnull", False)),
                    _connector="OR",
                ),
                name="durable_schedule_claim_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durablejob",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_digest__regex", "^[0-9a-f]{64}$")),
                name="durable_job_payload_digest_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durablejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result_digest", ""),
                    ("result_digest__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="durable_job_result_digest_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durablejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("job_type__regex", "^[a-z][a-z0-9_.:-]{2,95}$"),
                    ("idempotency_key__regex", "^[a-z][a-z0-9_.:-]{2,127}$"),
                    ("owner_ref__regex", "^[a-z][a-z0-9_.:-]{2,127}$"),
                ),
                name="durable_job_identity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsalertdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_expires_at__isnull", False),
                        ("claim_token__isnull", False),
                        ("status", "sending"),
                    ),
                    models.Q(
                        models.Q(("status", "sending"), _negated=True),
                        ("claim_expires_at__isnull", True),
                        ("claim_token__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_delivery_claim_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationshealthsample",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("observed_at"))),
                name="operations_health_expiry_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.UniqueConstraint(
                fields=("site_id", "environment", "fingerprint"),
                name="operations_incident_environment_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_observed_at__gte", models.F("first_observed_at"))),
                name="operations_incident_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolved_at__isnull", False), ("state", "resolved")),
                    models.Q(
                        models.Q(("state", "resolved"), _negated=True),
                        ("resolved_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_incident_resolution_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical", False), ("state", "active"), _connector="OR"),
                name="tenant_domain_canonical_state_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ("verified", "active")), _negated=True),
                    models.Q(
                        ("verified_at__isnull", False),
                        models.Q(("evidence_digest", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tenant_domain_verification_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "active"), _negated=True),
                    models.Q(
                        models.Q(("approval_digest", ""), _negated=True),
                        models.Q(("release_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tenant_domain_activation_ck",
            ),
        ),
        migrations.RunPython(narrow_worker_grants, restore_worker_grants),
    ]
