# Generated by Django 6.1 on 2026-09-08 08:10

import os
import re

from django.db import migrations, models

ROLE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,62}$")


def narrow_worker_grants(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE.fullmatch(worker):
        raise RuntimeError("runtime:workspace_worker_db_user_invalid")
    quoted = schema_editor.connection.ops.quote_name(worker)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'REVOKE INSERT, UPDATE ON TABLE "sitecontent_tenantdomainclaim" FROM {quoted}'
        )
        cursor.execute(
            f'REVOKE INSERT, UPDATE ON TABLE "sitecontent_breakglassgrant" FROM {quoted}'
        )
        cursor.execute(f'REVOKE INSERT ON TABLE "sitecontent_durableschedule" FROM {quoted}')
        cursor.execute(f'REVOKE INSERT ON TABLE "sitecontent_tenantnotification" FROM {quoted}')


def restore_worker_grants(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    worker = os.environ.get("WORKSPACE_WORKER_DB_USER", "").strip()
    if not ROLE.fullmatch(worker):
        raise RuntimeError("runtime:workspace_worker_db_user_invalid")
    quoted = schema_editor.connection.ops.quote_name(worker)
    with schema_editor.connection.cursor() as cursor:
        for table in (
            "sitecontent_tenantdomainclaim",
            "sitecontent_breakglassgrant",
            "sitecontent_durableschedule",
            "sitecontent_tenantnotification",
        ):
            cursor.execute(f'GRANT INSERT, UPDATE ON TABLE "{table}" TO {quoted}')


class Migration(migrations.Migration):
    dependencies = [
        ("sitecontent", "0025_runtime_governance_rls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="operationsincident",
            name="operations_incident_scope_uq",
        ),
        migrations.AddField(
            model_name="durablejob",
            name="lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="durableschedule",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="durableschedule",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsalertdelivery",
            name="claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsalertdelivery",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationsincident",
            name="environment",
            field=models.CharField(
                choices=[
                    ("preview", "Preview"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                ],
                default="preview",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="operationsalertdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("acknowledged", "Acknowledged"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="breakglassgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("requester_ref", models.F("approver_ref")), _negated=True),
                name="break_glass_independent_approver_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durablejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_token__isnull", False),
                        ("state", "leased"),
                        models.Q(("lease_owner", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("state", "leased"), _negated=True),
                        ("lease_owner", ""),
                        ("lease_token__isnull", True),
                        ("lease_expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="durable_job_lease_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="durableschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("claim_expires_at__isnull", True), ("claim_token__isnull", True)),
                    models.Q(("claim_expires_at__isnull", False), ("claim_token__isnull", False)),
                    _connector="OR",
                ),
                name="durable_schedule_claim_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsalertdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claim_expires_at__isnull", False),
                        ("claim_token__isnull", False),
                        ("status", "sending"),
                    ),
                    models.Q(
                        models.Q(("status", "sending"), _negated=True),
                        ("claim_expires_at__isnull", True),
                        ("claim_token__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_delivery_claim_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationshealthsample",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("observed_at"))),
                name="operations_health_expiry_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.UniqueConstraint(
                fields=("site_id", "environment", "fingerprint"),
                name="operations_incident_environment_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_observed_at__gte", models.F("first_observed_at"))),
                name="operations_incident_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationsincident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolved_at__isnull", False), ("state", "resolved")),
                    models.Q(
                        models.Q(("state", "resolved"), _negated=True),
                        ("resolved_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_incident_resolution_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical", False), ("state", "active"), _connector="OR"),
                name="tenant_domain_canonical_state_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ("verified", "active")), _negated=True),
                    models.Q(
                        ("verified_at__isnull", False),
                        models.Q(("evidence_digest", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tenant_domain_verification_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantdomainclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "active"), _negated=True),
                    models.Q(
                        models.Q(("approval_digest", ""), _negated=True),
                        models.Q(("release_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tenant_domain_activation_ck",
            ),
        ),
        migrations.RunPython(narrow_worker_grants, restore_worker_grants),
    ]
