# Generated by Django 6.0 on 2026-01-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Updated', 'verbose_name_plural': 'Updated On'},
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date/Time last updated in database', verbose_name='Last Updated On'),
        ),
    ]
