DatabaseDirectory /var/lib/clamav
CVDCertsDirectory /etc/clamav/certs
DatabaseOwner clamav
DatabaseMirror database.clamav.net
ScriptedUpdates yes
TestDatabases yes
CompressLocalDatabase yes
ConnectTimeout 10
ReceiveTimeout 10
MaxAttempts 2
