name: ci-load

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain (e.g., websitedomain)'
        required: true
        type: string

jobs:
  k6-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - name: Run k6 smoke
        uses: grafana/k6-action@e4714b734f2b0afaabeb7b4a69142745548ab9ec
        with:
          filename: load/k6/smoke.js
        env:
          DOMAIN: ${{ inputs.domain }}
